export default {
  data: [
    {
      id: 2282,
      userName: "supriya51@redmatter.com",
      firstName: "testa",
      middleNames: null,
      lastName: "salesforce",
      sipExtension: "2002",
      primaryMobileNumber: "",
      permissionLevel: "BASIC",
      enabled: true,
      primaryGroupId: null,
      availabilityProfileId: null,
      availabilityStateId: null,
      memberOf: [],
      sipDevices: [],
      pciEnabled: false,
      scopes: ["insight:basic", "insights:basic"],
    },
    {
      id: 2294,
      userName: "supriya5@redmatter.com",
      firstName: "Sups",
      lastName: "P",
      sipExtension: "2001",
      availabilityProfile: null,
      availabilityState: null,
    },
    {
      id: 2823,
      userName: "sups2@test.com",
      firstName: "Dominic",
      lastName: "P",
      sipExtension: "2003",
      availabilityProfile: null,
      availabilityState: null,
    },
    {
      id: 3071,
      userName: "supstest@gmail.com.sandbox00d24000000fgraeaa",
      firstName: "Sups",
      lastName: "Pr",
      sipExtension: "2010",
      availabilityProfile: null,
      availabilityState: null,
    },
  ],
}

export const getUserStub = {
  data: {
    id: 2282,
    userName: "supriya51@redmatter.com",
    firstName: "testa",
    middleNames: null,
    lastName: "salesforce",
    sipExtension: "2002",
    primaryMobileNumber: "",
    permissionLevel: "BASIC",
    enabled: true,
    primaryGroupId: null,
    availabilityProfileId: null,
    availabilityStateId: null,
    memberOf: [],
    sipDevices: [],
    pciEnabled: false,
    scopes: ["insight:basic", "insights:basic"],
  },
}

export const createUserStub = {
  id: 8510,
  password: "UP]ww8O)5*63p,^a",
  data: {
    userName: "sukeshjph@gmail.com",
    firstName: "Sukesh",
    middleNames: "Kumar",
    lastName: "Dash",
    sipExtension: "6999",
    primaryMobileNumber: "09766644444",
    permissionLevel: "BASIC",
    enabled: true,
    primaryGroupId: null,
    availabilityProfileId: null,
    availabilityStateId: null,
    memberOf: [],
    sipDevices: [],
    pciEnabled: false,
  },
}

export const updateUserStub = {
  password: "9!^7mu[Y8VNjz+dB",
  data: {
    userName: "sukujph1@gmail.com",
    firstName: "sukuiii",
    middleNames: "Kumar1",
    lastName: "Dash1",
    sipExtension: null,
    primaryMobileNumber: "07415673450",
    permissionLevel: "BASIC",
    enabled: true,
    primaryGroupId: null,
    availabilityProfileId: null,
    availabilityStateId: null,
    memberOf: [],
    sipDevices: null,
    pciEnabled: false,
  },
}

export const deleteUserStub = {
  data: {},
}
