export const timeZones = [
  { Label: "Africa/Abidjan", Val: "Africa/Abidjan" },
  { Label: "Africa/Accra", Val: "Africa/Accra" },
  { Label: "Africa/Addis_Ababa", Val: "Africa/Addis_Ababa" },
  { Label: "Africa/Algiers", Val: "Africa/Algiers" },
  { Label: "Africa/Asmara", Val: "Africa/Asmara" },
  { Label: "Africa/Asmera", Val: "Africa/Asmera" },
  { Label: "Africa/Bamako", Val: "Africa/Bamako" },
  { Label: "Africa/Bangui", Val: "Africa/Bangui" },
  { Label: "Africa/Banjul", Val: "Africa/Banjul" },
  { Label: "Africa/Bissau", Val: "Africa/Bissau" },
  { Label: "Africa/Blantyre", Val: "Africa/Blantyre" },
  { Label: "Africa/Brazzaville", Val: "Africa/Brazzaville" },
  { Label: "Africa/Bujumbura", Val: "Africa/Bujumbura" },
  { Label: "Africa/Cairo", Val: "Africa/Cairo" },
  { Label: "Africa/Casablanca", Val: "Africa/Casablanca" },
  { Label: "Africa/Ceuta", Val: "Africa/Ceuta" },
  { Label: "Africa/Conakry", Val: "Africa/Conakry" },
  { Label: "Africa/Dakar", Val: "Africa/Dakar" },
  { Label: "Africa/Dar_es_Salaam", Val: "Africa/Dar_es_Salaam" },
  { Label: "Africa/Djibouti", Val: "Africa/Djibouti" },
  { Label: "Africa/Douala", Val: "Africa/Douala" },
  { Label: "Africa/El_Aaiun", Val: "Africa/El_Aaiun" },
  { Label: "Africa/Freetown", Val: "Africa/Freetown" },
  { Label: "Africa/Gaborone", Val: "Africa/Gaborone" },
  { Label: "Africa/Harare", Val: "Africa/Harare" },
  { Label: "Africa/Johannesburg", Val: "Africa/Johannesburg" },
  { Label: "Africa/Kampala", Val: "Africa/Kampala" },
  { Label: "Africa/Khartoum", Val: "Africa/Khartoum" },
  { Label: "Africa/Kigali", Val: "Africa/Kigali" },
  { Label: "Africa/Kinshasa", Val: "Africa/Kinshasa" },
  { Label: "Africa/Lagos", Val: "Africa/Lagos" },
  { Label: "Africa/Libreville", Val: "Africa/Libreville" },
  { Label: "Africa/Lome", Val: "Africa/Lome" },
  { Label: "Africa/Luanda", Val: "Africa/Luanda" },
  { Label: "Africa/Lubumbashi", Val: "Africa/Lubumbashi" },
  { Label: "Africa/Lusaka", Val: "Africa/Lusaka" },
  { Label: "Africa/Malabo", Val: "Africa/Malabo" },
  { Label: "Africa/Maputo", Val: "Africa/Maputo" },
  { Label: "Africa/Maseru", Val: "Africa/Maseru" },
  { Label: "Africa/Mbabane", Val: "Africa/Mbabane" },
  { Label: "Africa/Mogadishu", Val: "Africa/Mogadishu" },
  { Label: "Africa/Monrovia", Val: "Africa/Monrovia" },
  { Label: "Africa/Nairobi", Val: "Africa/Nairobi" },
  { Label: "Africa/Ndjamena", Val: "Africa/Ndjamena" },
  { Label: "Africa/Niamey", Val: "Africa/Niamey" },
  { Label: "Africa/Nouakchott", Val: "Africa/Nouakchott" },
  { Label: "Africa/Ouagadougou", Val: "Africa/Ouagadougou" },
  { Label: "Africa/Porto-Novo", Val: "Africa/Porto-Novo" },
  { Label: "Africa/Sao_Tome", Val: "Africa/Sao_Tome" },
  { Label: "Africa/Timbuktu", Val: "Africa/Timbuktu" },
  { Label: "Africa/Tripoli", Val: "Africa/Tripoli" },
  { Label: "Africa/Tunis", Val: "Africa/Tunis" },
  { Label: "Africa/Windhoek", Val: "Africa/Windhoek" },
  { Label: "America/Adak", Val: "America/Adak" },
  { Label: "America/Anchorage", Val: "America/Anchorage" },
  { Label: "America/Anguilla", Val: "America/Anguilla" },
  { Label: "America/Antigua", Val: "America/Antigua" },
  { Label: "America/Araguaina", Val: "America/Araguaina" },
  {
    Label: "America/Argentina/Buenos_Aires",
    Val: "America/Argentina/Buenos_Aires",
  },
  { Label: "America/Argentina/Catamarca", Val: "America/Argentina/Catamarca" },
  {
    Label: "America/Argentina/ComodRivadavia",
    Val: "America/Argentina/ComodRivadavia",
  },
  { Label: "America/Argentina/Cordoba", Val: "America/Argentina/Cordoba" },
  { Label: "America/Argentina/Jujuy", Val: "America/Argentina/Jujuy" },
  { Label: "America/Argentina/La_Rioja", Val: "America/Argentina/La_Rioja" },
  { Label: "America/Argentina/Mendoza", Val: "America/Argentina/Mendoza" },
  {
    Label: "America/Argentina/Rio_Gallegos",
    Val: "America/Argentina/Rio_Gallegos",
  },
  { Label: "America/Argentina/Salta", Val: "America/Argentina/Salta" },
  { Label: "America/Argentina/San_Juan", Val: "America/Argentina/San_Juan" },
  { Label: "America/Argentina/San_Luis", Val: "America/Argentina/San_Luis" },
  { Label: "America/Argentina/Tucuman", Val: "America/Argentina/Tucuman" },
  { Label: "America/Argentina/Ushuaia", Val: "America/Argentina/Ushuaia" },
  { Label: "America/Aruba", Val: "America/Aruba" },
  { Label: "America/Asuncion", Val: "America/Asuncion" },
  { Label: "America/Atikokan", Val: "America/Atikokan" },
  { Label: "America/Atka", Val: "America/Atka" },
  {
    Label: "America/Bahia",
    Val: "America/Bahia",
  },
  { Label: "America/Barbados", Val: "America/Barbados" },
  { Label: "America/Belem", Val: "America/Belem" },
  { Label: "America/Belize", Val: "America/Belize" },
  { Label: "America/Blanc-Sablon", Val: "America/Blanc-Sablon" },
  { Label: "America/Boa_Vista", Val: "America/Boa_Vista" },
  { Label: "America/Bogota", Val: "America/Bogota" },
  { Label: "America/Boise", Val: "America/Boise" },
  { Label: "America/Buenos_Aires", Val: "America/Buenos_Aires" },
  { Label: "America/Cambridge_Bay", Val: "America/Cambridge_Bay" },
  { Label: "America/Campo_Grande", Val: "America/Campo_Grande" },
  { Label: "America/Cancun", Val: "America/Cancun" },
  { Label: "America/Caracas", Val: "America/Caracas" },
  { Label: "America/Catamarca", Val: "America/Catamarca" },
  { Label: "America/Cayenne", Val: "America/Cayenne" },
  { Label: "America/Cayman", Val: "America/Cayman" },
  { Label: "America/Chicago", Val: "America/Chicago" },
  { Label: "America/Chihuahua", Val: "America/Chihuahua" },
  { Label: "America/Coral_Harbour", Val: "America/Coral_Harbour" },
  { Label: "America/Cordoba", Val: "America/Cordoba" },
  { Label: "America/Costa_Rica", Val: "America/Costa_Rica" },
  { Label: "America/Cuiaba", Val: "America/Cuiaba" },
  { Label: "America/Curacao", Val: "America/Curacao" },
  { Label: "America/Danmarkshavn", Val: "America/Danmarkshavn" },
  { Label: "America/Dawson", Val: "America/Dawson" },
  { Label: "America/Dawson_Creek", Val: "America/Dawson_Creek" },
  { Label: "America/Denver", Val: "America/Denver" },
  { Label: "America/Detroit", Val: "America/Detroit" },
  { Label: "America/Dominica", Val: "America/Dominica" },
  { Label: "America/Edmonton", Val: "America/Edmonton" },
  { Label: "America/Eirunepe", Val: "America/Eirunepe" },
  { Label: "America/El_Salvador", Val: "America/El_Salvador" },
  { Label: "America/Ensenada", Val: "America/Ensenada" },
  { Label: "America/Fort_Wayne", Val: "America/Fort_Wayne" },
  { Label: "America/Fortaleza", Val: "America/Fortaleza" },
  { Label: "America/Glace_Bay", Val: "America/Glace_Bay" },
  { Label: "America/Godthab", Val: "America/Godthab" },
  { Label: "America/Goose_Bay", Val: "America/Goose_Bay" },
  { Label: "America/Grand_Turk", Val: "America/Grand_Turk" },
  { Label: "America/Grenada", Val: "America/Grenada" },
  { Label: "America/Guadeloupe", Val: "America/Guadeloupe" },
  { Label: "America/Guatemala", Val: "America/Guatemala" },
  { Label: "America/Guayaquil", Val: "America/Guayaquil" },
  { Label: "America/Guyana", Val: "America/Guyana" },
  { Label: "America/Halifax", Val: "America/Halifax" },
  { Label: "America/Havana", Val: "America/Havana" },
  { Label: "America/Hermosillo", Val: "America/Hermosillo" },
  {
    Label: "America/Indiana/Indianapolis",
    Val: "America/Indiana/Indianapolis",
  },
  { Label: "America/Indiana/Knox", Val: "America/Indiana/Knox" },
  { Label: "America/Indiana/Marengo", Val: "America/Indiana/Marengo" },
  { Label: "America/Indiana/Petersburg", Val: "America/Indiana/Petersburg" },
  { Label: "America/Indiana/Tell_City", Val: "America/Indiana/Tell_City" },
  { Label: "America/Indiana/Vevay", Val: "America/Indiana/Vevay" },
  { Label: "America/Indiana/Vincennes", Val: "America/Indiana/Vincennes" },
  { Label: "America/Indiana/Winamac", Val: "America/Indiana/Winamac" },
  { Label: "America/Indianapolis", Val: "America/Indianapolis" },
  { Label: "America/Inuvik", Val: "America/Inuvik" },
  { Label: "America/Iqaluit", Val: "America/Iqaluit" },
  { Label: "America/Jamaica", Val: "America/Jamaica" },
  { Label: "America/Jujuy", Val: "America/Jujuy" },
  { Label: "America/Juneau", Val: "America/Juneau" },
  { Label: "America/Kentucky/Louisville", Val: "America/Kentucky/Louisville" },
  { Label: "America/Kentucky/Monticello", Val: "America/Kentucky/Monticello" },
  { Label: "America/Knox_IN", Val: "America/Knox_IN" },
  { Label: "America/La_Paz", Val: "America/La_Paz" },
  { Label: "America/Lima", Val: "America/Lima" },
  { Label: "America/Los_Angeles", Val: "America/Los_Angeles" },
  { Label: "America/Louisville", Val: "America/Louisville" },
  { Label: "America/Maceio", Val: "America/Maceio" },
  { Label: "America/Managua", Val: "America/Managua" },
  { Label: "America/Manaus", Val: "America/Manaus" },
  { Label: "America/Marigot", Val: "America/Marigot" },
  { Label: "America/Martinique", Val: "America/Martinique" },
  { Label: "America/Matamoros", Val: "America/Matamoros" },
  { Label: "America/Mazatlan", Val: "America/Mazatlan" },
  { Label: "America/Mendoza", Val: "America/Mendoza" },
  { Label: "America/Menominee", Val: "America/Menominee" },
  { Label: "America/Merida", Val: "America/Merida" },
  { Label: "America/Mexico_City", Val: "America/Mexico_City" },
  { Label: "America/Miquelon", Val: "America/Miquelon" },
  { Label: "America/Moncton", Val: "America/Moncton" },
  { Label: "America/Monterrey", Val: "America/Monterrey" },
  { Label: "America/Montevideo", Val: "America/Montevideo" },
  { Label: "America/Montreal", Val: "America/Montreal" },
  { Label: "America/Montserrat", Val: "America/Montserrat" },
  { Label: "America/Nassau", Val: "America/Nassau" },
  { Label: "America/New_York", Val: "America/New_York" },
  { Label: "America/Nipigon", Val: "America/Nipigon" },
  { Label: "America/Nome", Val: "America/Nome" },
  { Label: "America/Noronha", Val: "America/Noronha" },
  { Label: "America/North_Dakota/Center", Val: "America/North_Dakota/Center" },
  {
    Label: "America/North_Dakota/New_Salem",
    Val: "America/North_Dakota/New_Salem",
  },
  { Label: "America/Ojinaga", Val: "America/Ojinaga" },
  { Label: "America/Panama", Val: "America/Panama" },
  { Label: "America/Pangnirtung", Val: "America/Pangnirtung" },
  { Label: "America/Paramaribo", Val: "America/Paramaribo" },
  { Label: "America/Phoenix", Val: "America/Phoenix" },
  { Label: "America/Port-au-Prince", Val: "America/Port-au-Prince" },
  { Label: "America/Port_of_Spain", Val: "America/Port_of_Spain" },
  { Label: "America/Porto_Acre", Val: "America/Porto_Acre" },
  { Label: "America/Porto_Velho", Val: "America/Porto_Velho" },
  { Label: "America/Puerto_Rico", Val: "America/Puerto_Rico" },
  { Label: "America/Rainy_River", Val: "America/Rainy_River" },
  { Label: "America/Rankin_Inlet", Val: "America/Rankin_Inlet" },
  { Label: "America/Recife", Val: "America/Recife" },
  { Label: "America/Regina", Val: "America/Regina" },
  { Label: "America/Resolute", Val: "America/Resolute" },
  { Label: "America/Rio_Branco", Val: "America/Rio_Branco" },
  { Label: "America/Rosario", Val: "America/Rosario" },
  { Label: "America/Santa_Isabel", Val: "America/Santa_Isabel" },
  { Label: "America/Santarem", Val: "America/Santarem" },
  { Label: "America/Santiago", Val: "America/Santiago" },
  { Label: "America/Santo_Domingo", Val: "America/Santo_Domingo" },
  { Label: "America/Sao_Paulo", Val: "America/Sao_Paulo" },
  { Label: "America/Scoresbysund", Val: "America/Scoresbysund" },
  { Label: "America/Shiprock", Val: "America/Shiprock" },
  { Label: "America/St_Barthelemy", Val: "America/St_Barthelemy" },
  { Label: "America/St_Johns", Val: "America/St_Johns" },
  { Label: "America/St_Kitts", Val: "America/St_Kitts" },
  { Label: "America/St_Lucia", Val: "America/St_Lucia" },
  { Label: "America/St_Thomas", Val: "America/St_Thomas" },
  { Label: "America/St_Vincent", Val: "America/St_Vincent" },
  { Label: "America/Swift_Current", Val: "America/Swift_Current" },
  { Label: "America/Tegucigalpa", Val: "America/Tegucigalpa" },
  { Label: "America/Thule", Val: "America/Thule" },
  { Label: "America/Thunder_Bay", Val: "America/Thunder_Bay" },
  { Label: "America/Tijuana", Val: "America/Tijuana" },
  { Label: "America/Toronto", Val: "America/Toronto" },
  { Label: "America/Tortola", Val: "America/Tortola" },
  { Label: "America/Vancouver", Val: "America/Vancouver" },
  { Label: "America/Virgin", Val: "America/Virgin" },
  { Label: "America/Whitehorse", Val: "America/Whitehorse" },
  { Label: "America/Winnipeg", Val: "America/Winnipeg" },
  { Label: "America/Yakutat", Val: "America/Yakutat" },
  { Label: "America/Yellowknife", Val: "America/Yellowknife" },
  { Label: "Antarctica/Casey", Val: "Antarctica/Casey" },
  { Label: "Antarctica/Davis", Val: "Antarctica/Davis" },
  { Label: "Antarctica/DumontDUrville", Val: "Antarctica/DumontDUrville" },
  { Label: "Antarctica/Macquarie", Val: "Antarctica/Macquarie" },
  { Label: "Antarctica/Mawson", Val: "Antarctica/Mawson" },
  { Label: "Antarctica/McMurdo", Val: "Antarctica/McMurdo" },
  { Label: "Antarctica/Palmer", Val: "Antarctica/Palmer" },
  { Label: "Antarctica/Rothera", Val: "Antarctica/Rothera" },
  { Label: "Antarctica/South_Pole", Val: "Antarctica/South_Pole" },
  { Label: "Antarctica/Syowa", Val: "Antarctica/Syowa" },
  { Label: "Antarctica/Vostok", Val: "Antarctica/Vostok" },
  { Label: "Arctic/Longyearbyen", Val: "Arctic/Longyearbyen" },
  { Label: "Asia/Aden", Val: "Asia/Aden" },
  { Label: "Asia/Almaty", Val: "Asia/Almaty" },
  { Label: "Asia/Amman", Val: "Asia/Amman" },
  { Label: "Asia/Anadyr", Val: "Asia/Anadyr" },
  { Label: "Asia/Aqtau", Val: "Asia/Aqtau" },
  { Label: "Asia/Aqtobe", Val: "Asia/Aqtobe" },
  { Label: "Asia/Ashgabat", Val: "Asia/Ashgabat" },
  { Label: "Asia/Ashkhabad", Val: "Asia/Ashkhabad" },
  { Label: "Asia/Baghdad", Val: "Asia/Baghdad" },
  { Label: "Asia/Bahrain", Val: "Asia/Bahrain" },
  { Label: "Asia/Baku", Val: "Asia/Baku" },
  { Label: "Asia/Bangkok", Val: "Asia/Bangkok" },
  { Label: "Asia/Beirut", Val: "Asia/Beirut" },
  { Label: "Asia/Bishkek", Val: "Asia/Bishkek" },
  { Label: "Asia/Brunei", Val: "Asia/Brunei" },
  { Label: "Asia/Calcutta", Val: "Asia/Calcutta" },
  { Label: "Asia/Choibalsan", Val: "Asia/Choibalsan" },
  { Label: "Asia/Chongqing", Val: "Asia/Chongqing" },
  { Label: "Asia/Chungking", Val: "Asia/Chungking" },
  { Label: "Asia/Colombo", Val: "Asia/Colombo" },
  { Label: "Asia/Dacca", Val: "Asia/Dacca" },
  { Label: "Asia/Damascus", Val: "Asia/Damascus" },
  { Label: "Asia/Dhaka", Val: "Asia/Dhaka" },
  { Label: "Asia/Dili", Val: "Asia/Dili" },
  { Label: "Asia/Dubai", Val: "Asia/Dubai" },
  { Label: "Asia/Dushanbe", Val: "Asia/Dushanbe" },
  { Label: "Asia/Gaza", Val: "Asia/Gaza" },
  { Label: "Asia/Harbin", Val: "Asia/Harbin" },
  { Label: "Asia/Ho_Chi_Minh", Val: "Asia/Ho_Chi_Minh" },
  { Label: "Asia/Hong_Kong", Val: "Asia/Hong_Kong" },
  { Label: "Asia/Hovd", Val: "Asia/Hovd" },
  { Label: "Asia/Irkutsk", Val: "Asia/Irkutsk" },
  { Label: "Asia/Istanbul", Val: "Asia/Istanbul" },
  { Label: "Asia/Jakarta", Val: "Asia/Jakarta" },
  { Label: "Asia/Jayapura", Val: "Asia/Jayapura" },
  { Label: "Asia/Jerusalem", Val: "Asia/Jerusalem" },
  { Label: "Asia/Kabul", Val: "Asia/Kabul" },
  { Label: "Asia/Kamchatka", Val: "Asia/Kamchatka" },
  { Label: "Asia/Karachi", Val: "Asia/Karachi" },
  { Label: "Asia/Kashgar", Val: "Asia/Kashgar" },
  { Label: "Asia/Kathmandu", Val: "Asia/Kathmandu" },
  { Label: "Asia/Katmandu", Val: "Asia/Katmandu" },
  { Label: "Asia/Kolkata", Val: "Asia/Kolkata" },
  { Label: "Asia/Krasnoyarsk", Val: "Asia/Krasnoyarsk" },
  { Label: "Asia/Kuala_Lumpur", Val: "Asia/Kuala_Lumpur" },
  { Label: "Asia/Kuching", Val: "Asia/Kuching" },
  { Label: "Asia/Kuwait", Val: "Asia/Kuwait" },
  { Label: "Asia/Macao", Val: "Asia/Macao" },
  { Label: "Asia/Macau", Val: "Asia/Macau" },
  { Label: "Asia/Magadan", Val: "Asia/Magadan" },
  { Label: "Asia/Makassar", Val: "Asia/Makassar" },
  { Label: "Asia/Manila", Val: "Asia/Manila" },
  { Label: "Asia/Muscat", Val: "Asia/Muscat" },
  { Label: "Asia/Nicosia", Val: "Asia/Nicosia" },
  { Label: "Asia/Novokuznetsk", Val: "Asia/Novokuznetsk" },
  { Label: "Asia/Novosibirsk", Val: "Asia/Novosibirsk" },
  { Label: "Asia/Omsk", Val: "Asia/Omsk" },
  { Label: "Asia/Oral", Val: "Asia/Oral" },
  { Label: "Asia/Phnom_Penh", Val: "Asia/Phnom_Penh" },
  { Label: "Asia/Pontianak", Val: "Asia/Pontianak" },
  { Label: "Asia/Pyongyang", Val: "Asia/Pyongyang" },
  { Label: "Asia/Qatar", Val: "Asia/Qatar" },
  { Label: "Asia/Qyzylorda", Val: "Asia/Qyzylorda" },
  { Label: "Asia/Rangoon", Val: "Asia/Rangoon" },
  { Label: "Asia/Riyadh", Val: "Asia/Riyadh" },
  { Label: "Asia/Saigon", Val: "Asia/Saigon" },
  { Label: "Asia/Sakhalin", Val: "Asia/Sakhalin" },
  { Label: "Asia/Samarkand", Val: "Asia/Samarkand" },
  { Label: "Asia/Seoul", Val: "Asia/Seoul" },
  { Label: "Asia/Shanghai", Val: "Asia/Shanghai" },
  { Label: "Asia/Singapore", Val: "Asia/Singapore" },
  { Label: "Asia/Taipei", Val: "Asia/Taipei" },
  { Label: "Asia/Tashkent", Val: "Asia/Tashkent" },
  { Label: "Asia/Tbilisi", Val: "Asia/Tbilisi" },
  { Label: "Asia/Tehran", Val: "Asia/Tehran" },
  { Label: "Asia/Tel_Aviv", Val: "Asia/Tel_Aviv" },
  { Label: "Asia/Thimbu", Val: "Asia/Thimbu" },
  { Label: "Asia/Thimphu", Val: "Asia/Thimphu" },
  { Label: "Asia/Tokyo", Val: "Asia/Tokyo" },
  { Label: "Asia/Ujung_Pandang", Val: "Asia/Ujung_Pandang" },
  { Label: "Asia/Ulaanbaatar", Val: "Asia/Ulaanbaatar" },
  { Label: "Asia/Ulan_Bator", Val: "Asia/Ulan_Bator" },
  { Label: "Asia/Urumqi", Val: "Asia/Urumqi" },
  { Label: "Asia/Vientiane", Val: "Asia/Vientiane" },
  { Label: "Asia/Vladivostok", Val: "Asia/Vladivostok" },
  { Label: "Asia/Yakutsk", Val: "Asia/Yakutsk" },
  { Label: "Asia/Yekaterinburg", Val: "Asia/Yekaterinburg" },
  { Label: "Asia/Yerevan", Val: "Asia/Yerevan" },
  { Label: "Atlantic/Azores", Val: "Atlantic/Azores" },
  { Label: "Atlantic/Bermuda", Val: "Atlantic/Bermuda" },
  { Label: "Atlantic/Canary", Val: "Atlantic/Canary" },
  { Label: "Atlantic/Cape_Verde", Val: "Atlantic/Cape_Verde" },
  { Label: "Atlantic/Faeroe", Val: "Atlantic/Faeroe" },
  { Label: "Atlantic/Faroe", Val: "Atlantic/Faroe" },
  { Label: "Atlantic/Jan_Mayen", Val: "Atlantic/Jan_Mayen" },
  { Label: "Atlantic/Madeira", Val: "Atlantic/Madeira" },
  { Label: "Atlantic/Reykjavik", Val: "Atlantic/Reykjavik" },
  { Label: "Atlantic/South_Georgia", Val: "Atlantic/South_Georgia" },
  { Label: "Atlantic/St_Helena", Val: "Atlantic/St_Helena" },
  { Label: "Atlantic/Stanley", Val: "Atlantic/Stanley" },
  { Label: "Australia/ACT", Val: "Australia/ACT" },
  { Label: "Australia/Adelaide", Val: "Australia/Adelaide" },
  { Label: "Australia/Brisbane", Val: "Australia/Brisbane" },
  { Label: "Australia/Broken_Hill", Val: "Australia/Broken_Hill" },
  { Label: "Australia/Canberra", Val: "Australia/Canberra" },
  { Label: "Australia/Currie", Val: "Australia/Currie" },
  { Label: "Australia/Darwin", Val: "Australia/Darwin" },
  { Label: "Australia/Eucla", Val: "Australia/Eucla" },
  { Label: "Australia/Hobart", Val: "Australia/Hobart" },
  { Label: "Australia/LHI", Val: "Australia/LHI" },
  { Label: "Australia/Lindeman", Val: "Australia/Lindeman" },
  { Label: "Australia/Lord_Howe", Val: "Australia/Lord_Howe" },
  { Label: "Australia/Melbourne", Val: "Australia/Melbourne" },
  { Label: "Australia/North", Val: "Australia/North" },
  { Label: "Australia/NSW", Val: "Australia/NSW" },
  { Label: "Australia/Perth", Val: "Australia/Perth" },
  { Label: "Australia/Queensland", Val: "Australia/Queensland" },
  { Label: "Australia/South", Val: "Australia/South" },
  { Label: "Australia/Sydney", Val: "Australia/Sydney" },
  { Label: "Australia/Tasmania", Val: "Australia/Tasmania" },
  { Label: "Australia/Victoria", Val: "Australia/Victoria" },
  { Label: "Australia/West", Val: "Australia/West" },
  { Label: "Australia/Yancowinna", Val: "Australia/Yancowinna" },
  { Label: "Europe/Amsterdam", Val: "Europe/Amsterdam" },
  { Label: "Europe/Andorra", Val: "Europe/Andorra" },
  { Label: "Europe/Athens", Val: "Europe/Athens" },
  { Label: "Europe/Belfast", Val: "Europe/Belfast" },
  { Label: "Europe/Belgrade", Val: "Europe/Belgrade" },
  { Label: "Europe/Berlin", Val: "Europe/Berlin" },
  { Label: "Europe/Bratislava", Val: "Europe/Bratislava" },
  { Label: "Europe/Brussels", Val: "Europe/Brussels" },
  { Label: "Europe/Bucharest", Val: "Europe/Bucharest" },
  { Label: "Europe/Budapest", Val: "Europe/Budapest" },
  { Label: "Europe/Chisinau", Val: "Europe/Chisinau" },
  { Label: "Europe/Copenhagen", Val: "Europe/Copenhagen" },
  { Label: "Europe/Dublin", Val: "Europe/Dublin" },
  { Label: "Europe/Gibraltar", Val: "Europe/Gibraltar" },
  { Label: "Europe/Guernsey", Val: "Europe/Guernsey" },
  { Label: "Europe/Helsinki", Val: "Europe/Helsinki" },
  { Label: "Europe/Isle_of_Man", Val: "Europe/Isle_of_Man" },
  { Label: "Europe/Istanbul", Val: "Europe/Istanbul" },
  { Label: "Europe/Jersey", Val: "Europe/Jersey" },
  { Label: "Europe/Kaliningrad", Val: "Europe/Kaliningrad" },
  { Label: "Europe/Kiev", Val: "Europe/Kiev" },
  { Label: "Europe/Lisbon", Val: "Europe/Lisbon" },
  { Label: "Europe/Ljubljana", Val: "Europe/Ljubljana" },
  { Label: "Europe/London", Val: "Europe/London" },
  { Label: "Europe/Luxembourg", Val: "Europe/Luxembourg" },
  { Label: "Europe/Madrid", Val: "Europe/Madrid" },
  { Label: "Europe/Malta", Val: "Europe/Malta" },
  { Label: "Europe/Mariehamn", Val: "Europe/Mariehamn" },
  { Label: "Europe/Minsk", Val: "Europe/Minsk" },
  { Label: "Europe/Monaco", Val: "Europe/Monaco" },
  { Label: "Europe/Moscow", Val: "Europe/Moscow" },
  { Label: "Europe/Nicosia", Val: "Europe/Nicosia" },
  { Label: "Europe/Oslo", Val: "Europe/Oslo" },
  { Label: "Europe/Paris", Val: "Europe/Paris" },
  { Label: "Europe/Podgorica", Val: "Europe/Podgorica" },
  { Label: "Europe/Prague", Val: "Europe/Prague" },
  { Label: "Europe/Riga", Val: "Europe/Riga" },
  { Label: "Europe/Rome", Val: "Europe/Rome" },
  { Label: "Europe/Samara", Val: "Europe/Samara" },
  { Label: "Europe/San_Marino", Val: "Europe/San_Marino" },
  { Label: "Europe/Sarajevo", Val: "Europe/Sarajevo" },
  { Label: "Europe/Simferopol", Val: "Europe/Simferopol" },
  { Label: "Europe/Skopje", Val: "Europe/Skopje" },
  { Label: "Europe/Sofia", Val: "Europe/Sofia" },
  { Label: "Europe/Stockholm", Val: "Europe/Stockholm" },
  { Label: "Europe/Tallinn", Val: "Europe/Tallinn" },
  { Label: "Europe/Tirane", Val: "Europe/Tirane" },
  { Label: "Europe/Tiraspol", Val: "Europe/Tiraspol" },
  { Label: "Europe/Uzhgorod", Val: "Europe/Uzhgorod" },
  { Label: "Europe/Vaduz", Val: "Europe/Vaduz" },
  { Label: "Europe/Vatican", Val: "Europe/Vatican" },
  { Label: "Europe/Vienna", Val: "Europe/Vienna" },
  { Label: "Europe/Vilnius", Val: "Europe/Vilnius" },
  { Label: "Europe/Volgograd", Val: "Europe/Volgograd" },
  { Label: "Europe/Warsaw", Val: "Europe/Warsaw" },
  { Label: "Europe/Zagreb", Val: "Europe/Zagreb" },
  { Label: "Europe/Zaporozhye", Val: "Europe/Zaporozhye" },
  { Label: "Europe/Zurich", Val: "Europe/Zurich" },
  { Label: "Indian/Antananarivo", Val: "Indian/Antananarivo" },
  { Label: "Indian/Chagos", Val: "Indian/Chagos" },
  { Label: "Indian/Christmas", Val: "Indian/Christmas" },
  { Label: "Indian/Cocos", Val: "Indian/Cocos" },
  { Label: "Indian/Comoro", Val: "Indian/Comoro" },
  { Label: "Indian/Kerguelen", Val: "Indian/Kerguelen" },
  { Label: "Indian/Mahe", Val: "Indian/Mahe" },
  { Label: "Indian/Maldives", Val: "Indian/Maldives" },
  { Label: "Indian/Mauritius", Val: "Indian/Mauritius" },
  { Label: "Indian/Mayotte", Val: "Indian/Mayotte" },
  { Label: "Indian/Reunion", Val: "Indian/Reunion" },
  { Label: "Pacific/Apia", Val: "Pacific/Apia" },
  { Label: "Pacific/Auckland", Val: "Pacific/Auckland" },
  { Label: "Pacific/Chatham", Val: "Pacific/Chatham" },
  { Label: "Pacific/Easter", Val: "Pacific/Easter" },
  { Label: "Pacific/Efate", Val: "Pacific/Efate" },
  { Label: "Pacific/Enderbury", Val: "Pacific/Enderbury" },
  { Label: "Pacific/Fakaofo", Val: "Pacific/Fakaofo" },
  { Label: "Pacific/Fiji", Val: "Pacific/Fiji" },
  { Label: "Pacific/Funafuti", Val: "Pacific/Funafuti" },
  { Label: "Pacific/Galapagos", Val: "Pacific/Galapagos" },
  { Label: "Pacific/Gambier", Val: "Pacific/Gambier" },
  { Label: "Pacific/Guadalcanal", Val: "Pacific/Guadalcanal" },
  { Label: "Pacific/Guam", Val: "Pacific/Guam" },
  { Label: "Pacific/Honolulu", Val: "Pacific/Honolulu" },
  { Label: "Pacific/Johnston", Val: "Pacific/Johnston" },
  { Label: "Pacific/Kiritimati", Val: "Pacific/Kiritimati" },
  { Label: "Pacific/Kosrae", Val: "Pacific/Kosrae" },
  { Label: "Pacific/Kwajalein", Val: "Pacific/Kwajalein" },
  { Label: "Pacific/Majuro", Val: "Pacific/Majuro" },
  { Label: "Pacific/Marquesas", Val: "Pacific/Marquesas" },
  { Label: "Pacific/Midway", Val: "Pacific/Midway" },
  { Label: "Pacific/Nauru", Val: "Pacific/Nauru" },
  { Label: "Pacific/Niue", Val: "Pacific/Niue" },
  { Label: "Pacific/Norfolk", Val: "Pacific/Norfolk" },
  { Label: "Pacific/Noumea", Val: "Pacific/Noumea" },
  { Label: "Pacific/Pago_Pago", Val: "Pacific/Pago_Pago" },
  { Label: "Pacific/Palau", Val: "Pacific/Palau" },
  { Label: "Pacific/Pitcairn", Val: "Pacific/Pitcairn" },
  { Label: "Pacific/Ponape", Val: "Pacific/Ponape" },
  { Label: "Pacific/Port_Moresby", Val: "Pacific/Port_Moresby" },
  { Label: "Pacific/Rarotonga", Val: "Pacific/Rarotonga" },
  { Label: "Pacific/Saipan", Val: "Pacific/Saipan" },
  { Label: "Pacific/Samoa", Val: "Pacific/Samoa" },
  { Label: "Pacific/Tahiti", Val: "Pacific/Tahiti" },
  { Label: "Pacific/Tarawa", Val: "Pacific/Tarawa" },
  { Label: "Pacific/Tongatapu", Val: "Pacific/Tongatapu" },
  { Label: "Pacific/Truk", Val: "Pacific/Truk" },
  { Label: "Pacific/Wake", Val: "Pacific/Wake" },
  { Label: "Pacific/Wallis", Val: "Pacific/Wallis" },
  { Label: "Pacific/Yap", Val: "Pacific/Yap" },
]

export const CountryCodes = [
  { Country: "Austria", Code: "43" },
  { Country: "Australia", Code: "61" },
  { Country: "Belgium", Code: "32" },
  { Country: "Brazil", Code: "55" },
  { Country: "China", Code: "86" },
  { Country: "Czech Republic", Code: "420" },
  { Country: "Denmark", Code: "45" },
  { Country: "Estonia", Code: "372" },
  { Country: "Finland", Code: "358" },
  { Country: "France", Code: "33" },
  { Country: "Germany", Code: "49" },
  { Country: "Greece ", Code: "30" },
  { Country: "Hong Kong", Code: "852" },
  { Country: "Israel", Code: "972" },
  { Country: "Italy", Code: "39" },
  { Country: "Japan", Code: "81" },
  { Country: "Latvia", Code: "371" },
  { Country: "Lithuania", Code: "370" },
  { Country: "Mexico", Code: "52" },
  { Country: "Norway", Code: "47" },
  { Country: "Netherlands", Code: "31" },
  { Country: "Poland", Code: "48" },
  { Country: "Portugal", Code: "351" },
  { Country: "Rep. of Ireland", Code: "353" },
  { Country: "Singapore", Code: "65" },
  { Country: "Slovakia", Code: "421" },
  { Country: "South Africa", Code: "27" },
  { Country: "South Korea", Code: "82" },
  { Country: "Spain", Code: "34" },
  { Country: "Sweden", Code: "46" },
  { Country: "Switzerland", Code: "41" },
  { Country: "Thailand", Code: "66" },
  { Country: "Turkey", Code: "90" },
  { Country: "UAE", Code: "971" },
  { Country: "UK", Code: "44" },
  { Country: "USA, Canada", Code: "1" },
]

export const Voices = [
  {
    "Portal Name": "Mandarin (CN): Zhiyu",
    "Sapien Name": "CMN-CN_ZHIYU",
  },
  {
    "Portal Name": "Welsh (GB): Gwyneth",
    "Sapien Name": "CY_GWYNETH",
  },
  {
    "Portal Name": "Danish (DK): Anna-AI",
    "Sapien Name": "DA-DK_ANNA_AI",
  },
  {
    "Portal Name": "Danish (DK): Mads",
    "Sapien Name": "DA-DK_MADS",
  },
  {
    "Portal Name": "Danish (DK): Naja",
    "Sapien Name": "DA-DK_NAJA",
  },
  {
    "Portal Name": "German (DE): Elias-AI",
    "Sapien Name": "DE-DE_ELIAS_AI",
  },
  {
    "Portal Name": "German (DE): Erika-AI",
    "Sapien Name": "DE-DE_ERIKA_AI",
  },
  {
    "Portal Name": "German (DE): Hans",
    "Sapien Name": "DE_HANS",
  },
  {
    "Portal Name": "German (DE): Leonie-AI",
    "Sapien Name": "DE-DE_LEONIE_AI",
  },
  {
    "Portal Name": "German (DE): Marlene",
    "Sapien Name": "DE_MARLENE",
  },
  {
    "Portal Name": "German (DE): Martina-AI",
    "Sapien Name": "DE-DE_MARTINA_AI",
  },
  {
    "Portal Name": "German (DE): Oskar-AI",
    "Sapien Name": "DE-DE_OSKAR_AI",
  },
  {
    "Portal Name": "German (DE): Vicki",
    "Sapien Name": "DE-DE_VICKI",
  },
  {
    "Portal Name": "English (AU): Amelia-AI",
    "Sapien Name": "EN-AU_AMELIA_AI",
  },
  {
    "Portal Name": "English (AU): Nicole",
    "Sapien Name": "EN_NICOLE",
  },
  {
    "Portal Name": "English (AU): Noah-AI",
    "Sapien Name": "EN-AU_NOAH_AI",
  },
  {
    "Portal Name": "English (AU): Olivia-AI",
    "Sapien Name": "EN-AU_OLIVIA_AI",
  },
  {
    "Portal Name": "English (AU): Russell",
    "Sapien Name": "EN_RUSSELL",
  },
  {
    "Portal Name": "English (AU): William-AI",
    "Sapien Name": "EN-AU_WILLIAM_AI",
  },
  {
    "Portal Name": "English (GB): Amy",
    "Sapien Name": "EN-GB_AMY",
  },
  {
    "Portal Name": "English (GB): Brian",
    "Sapien Name": "EN-GB_BRIAN",
  },
  {
    "Portal Name": "English (GB): Emma",
    "Sapien Name": "EN_EMMA",
  },
  {
    "Portal Name": "English (GB): Hannah-AI",
    "Sapien Name": "EN-GB_HANNAH_AI",
  },
  {
    "Portal Name": "English (GB): Lewis-AI",
    "Sapien Name": "EN-GB_LEWIS_AI",
  },
  {
    "Portal Name": "English (GB): Lucy-AI",
    "Sapien Name": "EN-GB_LUCY_AI",
  },
  {
    "Portal Name": "English (GB): Thomas-AI",
    "Sapien Name": "EN-GB_THOMAS_AI",
  },
  {
    "Portal Name": "English (GB-WLS): Geraint",
    "Sapien Name": "CY_GERAINT",
  },
  {
    "Portal Name": "English (IN): Aditi",
    "Sapien Name": "EN-IN_ADITI",
  },
  {
    "Portal Name": "English (IN): Raveena",
    "Sapien Name": "EN-IN_RAVEENA",
  },
  {
    "Portal Name": "English (US): Emily-AI",
    "Sapien Name": "EN-US_EMILY_AI",
  },
  {
    "Portal Name": "English (US): Evelyn-AI",
    "Sapien Name": "EN-US_EVELYN_AI",
  },
  {
    "Portal Name": "English (US): Ivy",
    "Sapien Name": "EN_IVY",
  },
  {
    "Portal Name": "English (US): Joanna",
    "Sapien Name": "EN-US_JOANNA",
  },
  {
    "Portal Name": "English (US): Joey",
    "Sapien Name": "EN_JOEY",
  },
  {
    "Portal Name": "English (US): Justin",
    "Sapien Name": "EN-US_JUSTIN",
  },
  {
    "Portal Name": "English (US): Kendra",
    "Sapien Name": "EN_KENDRA",
  },
  {
    "Portal Name": "English (US): Kimberly",
    "Sapien Name": "EN_KIMBERLY",
  },
  {
    "Portal Name": "English (US): Liam-AI",
    "Sapien Name": "EN-US_LIAM_AI",
  },
  {
    "Portal Name": "English (US): Matthew",
    "Sapien Name": "EN-US_MATTHEW",
  },
  {
    "Portal Name": "English (US): Michael-AI",
    "Sapien Name": "EN-US_MICHAEL_AI",
  },
  {
    "Portal Name": "English (US): Oliver-AI",
    "Sapien Name": "EN-US_OLIVER_AI",
  },
  {
    "Portal Name": "English (US): Salli",
    "Sapien Name": "EN_SALLI",
  },
  {
    "Portal Name": "English (US): Sophia-AI",
    "Sapien Name": "EN-US_SOPHIA_AI",
  },
  {
    "Portal Name": "Spanish (ES): Conchita",
    "Sapien Name": "ES_CONCHITA",
  },
  {
    "Portal Name": "Spanish (ES): Enrique",
    "Sapien Name": "ES_ENRIQUE",
  },
  {
    "Portal Name": "Spanish (ES): Lucia",
    "Sapien Name": "ES-ES_LUCIA",
  },
  {
    "Portal Name": "Spanish (ES): Valeria-AI",
    "Sapien Name": "ES-ES_VALERIA_AI",
  },
  {
    "Portal Name": "Spanish (MX): Mia",
    "Sapien Name": "ES-MX_MIA",
  },
  {
    "Portal Name": "Spanish (US): Miguel",
    "Sapien Name": "ES_US_MIGUEL",
  },
  {
    "Portal Name": "Spanish (US): Penelope",
    "Sapien Name": "ES-US_PENELOPE",
  },
  {
    "Portal Name": "French (CA): Chantal",
    "Sapien Name": "FR_CA_CHANTAL",
  },
  {
    "Portal Name": "French (CA): Felix-AI",
    "Sapien Name": "FR-CA_FELIX_AI",
  },
  {
    "Portal Name": "French (CA): Florence-AI",
    "Sapien Name": "FR-CA_FLORENCE_AI",
  },
  {
    "Portal Name": "French (CA): Juliette-AI",
    "Sapien Name": "FR-CA_JULIETTE_AI",
  },
  {
    "Portal Name": "French (CA): Raphael-AI",
    "Sapien Name": "FR-CA_RAPHAEL_AI",
  },
  {
    "Portal Name": "French (FR): Adele-AI",
    "Sapien Name": "FR-FR_ADELE_AI",
  },
  {
    "Portal Name": "French (FR): Celine",
    "Sapien Name": "FR_CELINE",
  },
  {
    "Portal Name": "French (FR): Curtis-AI",
    "Sapien Name": "FR-FR_CURTIS_AI",
  },
  {
    "Portal Name": "French (FR): Danielle-AI",
    "Sapien Name": "FR-FR_DANIELLE_AI",
  },
  {
    "Portal Name": "French (FR): Jasper-AI",
    "Sapien Name": "FR-FR_JASPER_AI",
  },
  {
    "Portal Name": "French (FR): Lea",
    "Sapien Name": "FR-FR_LEA",
  },
  {
    "Portal Name": "French (FR): Mathieu",
    "Sapien Name": "FR_MATHIEU",
  },
  {
    "Portal Name": "Hindi (IN): Aditi",
    "Sapien Name": "HI-IN_ADITI",
  },
  {
    "Portal Name": "Icelandic (IS): Dora",
    "Sapien Name": "IS_DORA",
  },
  {
    "Portal Name": "Icelandic (IS): Karl",
    "Sapien Name": "IS_KARL",
  },
  {
    "Portal Name": "Italian (IT): Bianca",
    "Sapien Name": "IT-IT_BIANCA",
  },
  {
    "Portal Name": "Italian (IT): Carla",
    "Sapien Name": "IT_CARLA",
  },
  {
    "Portal Name": "Italian (IT): Giorgio",
    "Sapien Name": "IT_GIORGIO",
  },
  {
    "Portal Name": "Japanese (JP): Kanna-AI",
    "Sapien Name": "JA-JP_KANNA_AI",
  },
  {
    "Portal Name": "Japanese (JP): Mizuki",
    "Sapien Name": "JA-JP_MIZUKI",
  },
  {
    "Portal Name": "Japanese (JP): Takumi",
    "Sapien Name": "JA-JP_TAKUMI",
  },
  {
    "Portal Name": "Korean (KR): Hyun-AI",
    "Sapien Name": "KO-KR_HYUN_AI",
  },
  {
    "Portal Name": "Korean (KR): Ji-Su-AI",
    "Sapien Name": "KO-KR_JI-SU_AI",
  },
  {
    "Portal Name": "Korean (KR): Kwan-AI",
    "Sapien Name": "KO-KR_KWAN_AI",
  },
  {
    "Portal Name": "Korean (KR): Seo-Yun-AI",
    "Sapien Name": "KO-KR_SEO-YUN_AI",
  },
  {
    "Portal Name": "Korean (KR): Seoyeon",
    "Sapien Name": "KO-KR_SEOYEON",
  },
  {
    "Portal Name": "Norwegian (NO): Anita-AI",
    "Sapien Name": "NB-NO_ANITA_AI",
  },
  {
    "Portal Name": "Norwegian (NO): Liv",
    "Sapien Name": "NB_NO_LIV",
  },
  {
    "Portal Name": "Dutch (NL): Fleur-AI",
    "Sapien Name": "NL-NL_FLEUR_AI",
  },
  {
    "Portal Name": "Dutch (NL): Lotte",
    "Sapien Name": "NL_LOTTE",
  },
  {
    "Portal Name": "Dutch (NL): Ruben",
    "Sapien Name": "NL-NL_RUBEN",
  },
  {
    "Portal Name": "Polish (PL): Antoni-AI",
    "Sapien Name": "PL-PL_ANTONI_AI",
  },
  {
    "Portal Name": "Polish (PL): Dominik-AI",
    "Sapien Name": "PL-PL_DOMINIK_AI",
  },
  {
    "Portal Name": "Polish (PL): Elena-AI",
    "Sapien Name": "PL-PL_ELENA_AI",
  },
  {
    "Portal Name": "Polish (PL): Ewa",
    "Sapien Name": "PL_EWA",
  },
  {
    "Portal Name": "Polish (PL): Iga-AI",
    "Sapien Name": "PL-PL_IGA_AI",
  },
  {
    "Portal Name": "Polish (PL): Jacek",
    "Sapien Name": "PL_JACEK",
  },
  {
    "Portal Name": "Polish (PL): Jan",
    "Sapien Name": "PL_JAN",
  },
  {
    "Portal Name": "Polish (PL): Maja",
    "Sapien Name": "PL_MAJA",
  },
  {
    "Portal Name": "Polish (PL): Monika-AI",
    "Sapien Name": "PL-PL_MONIKA_AI",
  },
  {
    "Portal Name": "Portuguese (BR): Izabel-AI",
    "Sapien Name": "PT-BR_IZABEL_AI",
  },
  {
    "Portal Name": "Portuguese (BR): Ricardo",
    "Sapien Name": "PT_BR_RICARDO",
  },
  {
    "Portal Name": "Portuguese (BR): Vitoria",
    "Sapien Name": "PT_BR_VITORIA",
  },
  {
    "Portal Name": "Portuguese (PT): Adriano-AI",
    "Sapien Name": "PT-PT_ADRIANO_AI",
  },
  {
    "Portal Name": "Portuguese (PT): Cristiano",
    "Sapien Name": "PT-PT_CRISTIANO",
  },
  {
    "Portal Name": "Portuguese (PT): Ines",
    "Sapien Name": "PT-PT_INES",
  },
  {
    "Portal Name": "Portuguese (PT): Jeronimo-AI",
    "Sapien Name": "PT-PT_JERONIMO_AI",
  },
  {
    "Portal Name": "Portuguese (PT): Marissa-AI",
    "Sapien Name": "PT-PT_MARISSA_AI",
  },
  {
    "Portal Name": "Portuguese (PT): Rosa-AI",
    "Sapien Name": "PT-PT_ROSA_AI",
  },
  {
    "Portal Name": "Romanian (RO): Carmen",
    "Sapien Name": "RO_CARMEN",
  },
  {
    "Portal Name": "Russian (RU): Gennadi-AI",
    "Sapien Name": "RU-RU_GENNADI_AI",
  },
  {
    "Portal Name": "Russian (RU): Ivan-AI",
    "Sapien Name": "RU-RU_IVAN_AI",
  },
  {
    "Portal Name": "Russian (RU): Maxim",
    "Sapien Name": "RU-RU_MAXIM",
  },
  {
    "Portal Name": "Russian (RU): Natasha-AI",
    "Sapien Name": "RU-RU_NATASHA_AI",
  },
  {
    "Portal Name": "Russian (RU): Tanya-AI",
    "Sapien Name": "RU-RU_TANYA_AI",
  },
  {
    "Portal Name": "Russian (RU): Tatyana",
    "Sapien Name": "RU_TATYANA",
  },
  {
    "Portal Name": "Slovak (SK): Nina-AI",
    "Sapien Name": "SK-SK_NINA_AI",
  },
  {
    "Portal Name": "Swedish (SE): Astrid",
    "Sapien Name": "SV_SE_ASTRID",
  },
  {
    "Portal Name": "Swedish (SE): Elsa-AI",
    "Sapien Name": "SV-SE_ELSA_AI",
  },
  {
    "Portal Name": "Turkish (TR): Ayla-AI",
    "Sapien Name": "TR-TR_AYLA_AI",
  },
  {
    "Portal Name": "Turkish (TR): Filiz",
    "Sapien Name": "TR_FILIZ",
  },
  {
    "Portal Name": "Turkish (TR): Nesrin-AI",
    "Sapien Name": "TR-TR_NESRIN_AI",
  },
  {
    "Portal Name": "Turkish (TR): Omer-AI",
    "Sapien Name": "TR-TR_OMER_AI",
  },
  {
    "Portal Name": "Turkish (TR): Yesim-AI",
    "Sapien Name": "TR-TR_YESIM_AI",
  },
  {
    "Portal Name": "Turkish (TR): Yusef-AI",
    "Sapien Name": "TR-TR_YUSEF_AI",
  },
  {
    "Portal Name": "Ukrainian (UA): Liza-AI",
    "Sapien Name": "UK-UA_LIZA_AI",
  },
  {
    "Portal Name": "English (US): Chipmunk",
    "Sapien Name": "EN_CHIPMUNK",
  },
  {
    "Portal Name": "English (US): Eric",
    "Sapien Name": "EN_ERIC",
  },
  {
    "Portal Name": "English (US): Jennifer",
    "Sapien Name": "EN_JENNIFER",
  },
  {
    "Portal Name": "English (GB): Kate",
    "Sapien Name": "EN_KATE",
  },
  {
    "Portal Name": "English (GB): Simon",
    "Sapien Name": "EN_SIMON",
  },
  {
    "Portal Name": "Dutch (NL): Saskia",
    "Sapien Name": "NL_SASKIA",
  },
  {
    "Portal Name": "Dutch (NL): Willem",
    "Sapien Name": "NL_WILLEM",
  },
  {
    "Portal Name": "Polish (PL): Agnieszka",
    "Sapien Name": "PL_AGNIESZKA",
  },
]
